#!/bin/bash

# Generated by ChatGPT, 2025-07-23
# Absolutely! Below is a Bash script that generates a multilib.yaml (or template) with all main standard RISC-V ISA and ABI combinations commonly used in open toolchains, including most of the common 32- and 64-bit base/standard extension mixes.
# You can easily extend it for custom extensions or change directories as needed.
# Run it and redirect output:
# ./gen-multilib-yaml.sh > multilib.yaml
# Features:
# Covers common 32- and 64-bit ISA and ABI mixes (i, im, imc, imafc, imafdc, etc.)
#
# Skips impossible/invalid ISA+ABI combinations (e.g., no f in march → no ilp32f ABI)
#
# You can add more variants (e.g., rv32e, custom extensions) by editing the lists.




cat <<EOF
# SPDX-License-Identifier: Apache-2.0

MultilibVersion: '1.0'

Groups:
  - Name: stdlibs
    Type: Exclusive

Variants:
EOF

# RISC-V 32-bit architectures and ABIs
for march in rv32i rv32im rv32ic rv32imc rv32ia rv32ima rv32iac rv32imac rv32imafc; do
    for mabi in ilp32 ilp32f; do
        # Exclude incompatible ABI/ISA (e.g., ilp32f only valid with F extension)
        if [[ "$mabi" == "ilp32f" && "$march" != *f* ]]; then continue; fi
        dir="riscv32-unknown-elf/${march}/${mabi}"
        echo "  - Dir: $dir"
        echo "    Flags:"
        echo "      - --target=riscv32-unknown-elf"
        echo "      - -march=$march"
        echo "      - -mabi=$mabi"
        echo "    Group: stdlibs"
        echo ""
    done
done

# RISC-V 64-bit architectures and ABIs
for march in rv64i rv64im rv64ic rv64imc rv64ia rv64ima rv64iac rv64imac rv64imafc rv64imafdc; do
    for mabi in lp64 lp64f lp64d; do
        # Exclude incompatible ABI/ISA
        if [[ "$mabi" == "lp64f" && "$march" != *f* ]]; then continue; fi
        if [[ "$mabi" == "lp64d" && "$march" != *d* ]]; then continue; fi
        dir="riscv64-unknown-elf/${march}/${mabi}"
        echo "  - Dir: $dir"
        echo "    Flags:"
        echo "      - --target=riscv64-unknown-elf"
        echo "      - -march=$march"
        echo "      - -mabi=$mabi"
        echo "      - -mcmodel=medany"
        echo "    Group: stdlibs"
        echo ""
    done
done

cat <<EOF
Mappings:
EOF
